### ISSUE TITLE
Show error if you search for a crate that doesn't exist?

### ISSUE THREAD

**Issue by icefoxen** [LucianoBestia/cargo_crev_web#21]
Currently you can type `jfdskalfjdslafjdlsafjdksalfjdslafjdsalfjdlsa` into the "jump to crate" box and it will just take you to a page that shows no reviews.  It would be nice if it actually told you that the crate doesn't exist, rather than just saying "welp, wanna make a review for it?"

**Comment by LucianoBestia** [comment]
Yes, I don't have a list of all possible crates. Only a database of all crev reviews.
I am working now to process the "crates.io database dump" to get a list of all 42.000 crates. 
I will limit the data to only the last 10 non-yanked versions. 
There are crates with 600 non-yanked versions. Who needs that?
The api of crates.io and "crates.io index repo" are not really usable because they are made explicitly for cargo tools. They have a bunch of superfluous data and a bunch of missing data.
